name: Bug Report
description: Do you think you have found a bug? If so then file a bug report
title: "Bug Report: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Please include as much detail as possible about your Debian Supervised installation.
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Please run `hostnamectl` and insert the value after "Operating System"
      placeholder: Debian GNU/Linux 13 (bookworm)
    validations:
      required: true
  - type: input
    id: uname
    attributes:
      label: System Information
      description: Please insert the output of `uname -a`
      placeholder: 'Linux mcos 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux'
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please explain in detail, the issue you encountered and the steps to recreate it.
      placeholder: |
        I encountered an issue when trying to upgrade my existing installation to the Debian package.
        Steps to recreate:
        1. Install muthur-command-supervised on Debian 13
        2. Attempt to upgrade with dpkg -i as root
        3. The install fails with the error: ...
    validations:
      required: true
  - type: dropdown
    id: machine-type
    attributes:
      label: Machine Type
      description: Which machine type are you running?
      options:
        - generic-x86-64
        - khadas-vim3
        - odroid-c2
        - odroid-c4
        - odroid-n2
        - qemuarm-64
        - qemux86-64
        - raspberrypi3-64
        - raspberrypi4-64
        - raspberrypi5-64
    validations:
      required: true
  - type: textarea
    id: installer-output
    attributes:
      label: Installer output
      description: Please copy and paste any relevant output from the installer. This will be automatically formatted into code, so no need for backticks.
      render: text
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output from `journalctl -f`. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contribution guidelines.
      options:
        - label: I have reproduced this issue on a freshly installed, fully updated Debian 13 with no additional packages beyond the installation steps in README
          required: true
