blank_issues_enabled: true
contact_links:
  - name: Muthur Command Issues
    url: https://github.com/muthur-command/supervised-installer/issues
    about: Report installation issues for Muthur Command Supervised on Debian.
