#!/usr/bin/env bash
set -e
function info { echo -e "\e[32m[info] $*\e[39m"; }
function warn  { echo -e "\e[33m[warn] $*\e[39m"; }
function error { echo -e "\e[31m[error] $*\e[39m"; exit 1; }

warn ""
warn "If you want more control over your own system, run"
warn "Muthur Command as a VM or run Muthur Command Core"
warn "via a Docker container."
warn ""

# Check if we are running on a supported OS
BYPASS_OS_CHECK=${BYPASS_OS_CHECK:-false}
supported_os_id="debian"
supported_os_version_id=("13")

source /etc/os-release
os_supported=false

if [[ "$ID" == "$supported_os_id" ]]; then
    for version in "${supported_os_version_id[@]}"; do
        if [[ "$VERSION_ID" == "$version" ]]; then
            os_supported=true
            break
        fi
    done
fi

if [[ $os_supported == false ]]; then
    if [[ $BYPASS_OS_CHECK != "true" ]]; then
        error "${PRETTY_NAME} is not supported!"
    fi
    warn "Bypassing OS check..."
    warn "${PRETTY_NAME} is not supported!"
    warn "Please DO NOT report issues regarding this OS!"
fi

# Check if we are running on a supported architecture
ARCH=$(uname -m)
if [[ ! "x86_64|aarch64" == *"$ARCH"* ]]; then
    error "${ARCH} is not supported!"
fi

# Check if Modem Manager is enabled
if systemctl is-enabled ModemManager.service &> /dev/null; then
    warn "ModemManager service is enabled. This might cause issue when using serial devices."
fi

# Check dmesg access
if [[ "$(sysctl --values kernel.dmesg_restrict)" != "0" ]]; then
    info "Fix kernel dmesg restriction"
    echo 0 > /proc/sys/kernel/dmesg_restrict
    echo "kernel.dmesg_restrict=0" >> /etc/sysctl.conf
fi

# If the mcos_supervisor service is running, stop it
if [[ "$(systemctl is-active mcos-supervisor.service)" == "active" ]]; then
    info "Stopping mcos-supervisor service"
    systemctl stop mcos-supervisor.service
fi

# If the mcos-apparmor service is running, stop it
if [[ "$(systemctl is-active mcos-apparmor.service)" == "active" ]]; then
    info "Stopping mcos-apparmor service"
    systemctl stop mcos-apparmor.service
fi

# Check for existing mcos_supervisor container and destroy it
if [[ "$(docker ps -aq -f name=mcos_supervisor)" ]]; then
    info "Removing existing mcos_supervisor container"
    docker container rm --force mcos_supervisor > /dev/null
fi

dpkg-divert --package muthur-command-supervised --add --rename \
    --divert /etc/NetworkManager/NetworkManager.conf.real /etc/NetworkManager/NetworkManager.conf

dpkg-divert --package muthur-command-supervised --add --rename \
    --divert /etc/NetworkManager/system-connections/default.real /etc/NetworkManager/system-connections/default

dpkg-divert --package muthur-command-supervised --add --rename \
    --divert /etc/docker/daemon.json.real /etc/docker/daemon.json

dpkg-divert --package muthur-command-supervised --add --rename \
    --divert /etc/network/interfaces.real /etc/network/interfaces

dpkg-divert --package muthur-command-supervised --add --rename \
    --divert /etc/systemd/resolved.conf.real /etc/systemd/resolved.conf
